username:
  用户名
password:
  密码
journals:
  期刊1:
    # 这里是一个list，list里面每一项都是一个filter，满足所有filter的才会下载（即list中的元素求and）
    # y代表年份，m代表第几期，只要是合法的python表达式就可以（代码里面直接eval的）
    # 注意有些刊物有类似于"2017年第Z1期"，这种情况下对m操作无效
    # 如下例表示2000第三期到2010年之间
    - y>2000 or y==2000 and m>3
    - y<2010
  期刊2:
  期刊3:
